<script src="@/plugins/pagination/BootstrapPagination.js">
</script>
<template>
  <div>
    <b-table
      id="table_user"
      ref="userTable"
      :busy.sync="isBusy"
      :items="myProvider"
      :fields="fields"
      :per-page="perPage"
      :current-page="currentPage"
      show-empty>
      <template
        slot="operate"
        slot-scope="row">
        <b-button
          size="sm"
          class="mr-2"
          @click="detail(row.item.id)">
          Details
        </b-button>
        <b-button
          size="sm"
          class="mr-2"
          @click="deleteObj(row.item.id)">
          Delete
        </b-button>
      </template>
    </b-table>
    <b-row>
      <b-col
        md="6"
        class="my-1">
        <b-pagination
          v-model="currentPage"
          :total-rows="totalRows"
          :per-page="perPage"
          class="my-0"/>
      </b-col>
    </b-row>
  </div>
</template>
